---
# Sync wave 2: cert-manager must be running before these can be processed
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opensearch-operator-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-operator-serving-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  dnsNames:
  - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: opensearch-operator-selfsigned-issuer
  secretName: {{ .Release.Name }}-webhook-server-cert
---
# Sync wave 4: patch webhook configuration after webhook resources exist
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-validating-webhook-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/opensearch-operator-serving-cert"
